---
title: "feature engineering"
author: "author"
output:
  html_document:
    df_print: paged
    highlight: kate
    theme:
      version: 4
      code_font: 
        google: JetBrains Mono
editor_options:
  chunk_output_type: console
  markdown:
    wrap: 72
---

```{r}
library(data.table)
```

# paths

para poder usarlo en la PC y en la nube sin tener que cambiar la ruta cambiar aqui las rutas en su maquina
```{r}

switch(Sys.info()[["sysname"]],
  Darwin = {
    directory.root <- "~/code/austral/labo1/"
  }, # Apple MAC
  Linux = {
    directory.root <- "~/buckets/b1/"
  } # Google Cloud
)

# defino la carpeta donde trabajo
setwd(directory.root)
```

# read

```{r}
dataset <- fread(paste0(directory.root, "datasetsOri/paquete_premium.csv.gz"))
```

# errores del dataset

Esto viene de "~/code/austral/labo1/labo2021/clasesGustavo/TareasHogar/Tarea20210924/746_corrige.r"

```{r}
#acomodo los errores del dataset
dataset[foto_mes == 201801, internet := NA]
dataset[foto_mes == 201801, thomebanking := NA]
dataset[foto_mes == 201801, chomebanking_transacciones := NA]
dataset[foto_mes == 201801, tcallcenter := NA]
dataset[foto_mes == 201801, ccallcenter_transacciones := NA]
dataset[foto_mes == 201801, cprestamos_personales := NA]
dataset[foto_mes == 201801, mprestamos_personales := NA]
dataset[foto_mes == 201801, mprestamos_hipotecarios := NA]
dataset[foto_mes == 201801, ccajas_transacciones := NA]
dataset[foto_mes == 201801, ccajas_consultas := NA]
dataset[foto_mes == 201801, ccajas_depositos := NA]
dataset[foto_mes == 201801, ccajas_extracciones := NA]
dataset[foto_mes == 201801, ccajas_otras := NA]

dataset[foto_mes == 201806, tcallcenter := NA]
dataset[foto_mes == 201806, ccallcenter_transacciones := NA]

dataset[foto_mes == 201904, ctarjeta_visa_debitos_automaticos := NA]
dataset[foto_mes == 201904, mttarjeta_visa_debitos_automaticos := NA]
dataset[foto_mes == 201904, Visa_mfinanciacion_limite := NA]

dataset[foto_mes == 201905, mrentabilidad := NA]
dataset[foto_mes == 201905, mrentabilidad_annual := NA]
dataset[foto_mes == 201905, mcomisiones := NA]
dataset[foto_mes == 201905, mpasivos_margen := NA]
dataset[foto_mes == 201905, mactivos_margen := NA]
dataset[foto_mes == 201905, ctarjeta_visa_debitos_automaticos := NA]
dataset[foto_mes == 201905, ccomisiones_otras := NA]
dataset[foto_mes == 201905, mcomisiones_otras := NA]

dataset[foto_mes == 201910, mpasivos_margen := NA]
dataset[foto_mes == 201910, mactivos_margen := NA]
dataset[foto_mes == 201910, ccomisiones_otras := NA]
dataset[foto_mes == 201910, mcomisiones_otras := NA]
dataset[foto_mes == 201910, mcomisiones := NA]
dataset[foto_mes == 201910, mrentabilidad := NA]
dataset[foto_mes == 201910, mrentabilidad_annual := NA]
dataset[foto_mes == 201910, chomebanking_transacciones := NA]
dataset[foto_mes == 201910, ctarjeta_visa_descuentos := NA]
dataset[foto_mes == 201910, ctarjeta_master_descuentos := NA]
dataset[foto_mes == 201910, mtarjeta_visa_descuentos := NA]
dataset[foto_mes == 201910, mtarjeta_master_descuentos := NA]
dataset[foto_mes == 201910, ccajeros_propios_descuentos := NA]
dataset[foto_mes == 201910, mcajeros_propios_descuentos := NA]

dataset[foto_mes == 202001, cliente_vip := NA]

dataset[foto_mes == 202006, active_quarter := NA]
dataset[foto_mes == 202006, internet := NA]
dataset[foto_mes == 202006, mrentabilidad := NA]
dataset[foto_mes == 202006, mrentabilidad_annual := NA]
dataset[foto_mes == 202006, mcomisiones := NA]
dataset[foto_mes == 202006, mactivos_margen := NA]
dataset[foto_mes == 202006, mpasivos_margen := NA]
dataset[foto_mes == 202006, mcuentas_saldo := NA]
dataset[foto_mes == 202006, ctarjeta_debito_transacciones := NA]
dataset[foto_mes == 202006, mautoservicio := NA]
dataset[foto_mes == 202006, ctarjeta_visa_transacciones := NA]
dataset[foto_mes == 202006, mtarjeta_visa_consumo := NA]
dataset[foto_mes == 202006, ctarjeta_master_transacciones := NA]
dataset[foto_mes == 202006, mtarjeta_master_consumo := NA]
dataset[foto_mes == 202006, ccomisiones_otras := NA]
dataset[foto_mes == 202006, mcomisiones_otras := NA]
dataset[foto_mes == 202006, cextraccion_autoservicio := NA]
dataset[foto_mes == 202006, mextraccion_autoservicio := NA]
dataset[foto_mes == 202006, ccheques_depositados := NA]
dataset[foto_mes == 202006, mcheques_depositados := NA]
dataset[foto_mes == 202006, ccheques_emitidos := NA]
dataset[foto_mes == 202006, mcheques_emitidos := NA]
dataset[foto_mes == 202006, ccheques_depositados_rechazados := NA]
dataset[foto_mes == 202006, mcheques_depositados_rechazados := NA]
dataset[foto_mes == 202006, ccheques_emitidos_rechazados := NA]
dataset[foto_mes == 202006, mcheques_emitidos_rechazados := NA]
dataset[foto_mes == 202006, tcallcenter := NA]
dataset[foto_mes == 202006, ccallcenter_transacciones := NA]
dataset[foto_mes == 202006, thomebanking := NA]
dataset[foto_mes == 202006, chomebanking_transacciones := NA]
dataset[foto_mes == 202006, ccajas_transacciones := NA]
dataset[foto_mes == 202006, ccajas_consultas := NA]
dataset[foto_mes == 202006, ccajas_depositos := NA]
dataset[foto_mes == 202006, ccajas_extracciones := NA]
dataset[foto_mes == 202006, ccajas_otras := NA]
dataset[foto_mes == 202006, catm_trx := NA]
dataset[foto_mes == 202006, matm := NA]
dataset[foto_mes == 202006, catm_trx_other := NA]
dataset[foto_mes == 202006, matm_other := NA]
dataset[foto_mes == 202006, ctrx_quarter := NA]
dataset[foto_mes == 202006, tmobile_app := NA]
dataset[foto_mes == 202006, cmobile_app_trx := NA]


dataset[foto_mes == 202010, internet := NA]
dataset[foto_mes == 202011, internet := NA]
dataset[foto_mes == 202012, internet := NA]
dataset[foto_mes == 202101, internet := NA]

dataset[foto_mes == 202009, tmobile_app := NA]
dataset[foto_mes == 202010, tmobile_app := NA]
dataset[foto_mes == 202011, tmobile_app := NA]
dataset[foto_mes == 202012, tmobile_app := NA]
dataset[foto_mes == 202101, tmobile_app := NA]
```

Elimino mes de junio 2020, ya que esta bastante roto

```{r}
dataset <- dataset[foto_mes != 202006]
```

```{r}
fwrite(x = dataset, file = paste0(directory.root, "datasets/2021-09-30_paquete_premium_corregido_ordered_nojune.csv.gz"))
```

